### PR TITLE
Implement pagination (changes the API, so the example is changed too).

### PR DESCRIPTION
**Pull request by sillygwailo**

### CODE REVIEW

**Comment by sillygwailo** [comment]
To get all the books in a shelf, you will have to recurse through the shelves. [A .forEach() won't cut it, since it's non-blocking.](http://stackoverflow.com/questions/5050265/javascript-node-js-is-array-foreach-asynchronous) Instead use an algorithm similar to [the one Jordan Hoff used for looping through all his friends in the Graph API](http://jordanhoff.com/post/23278707137/recursive-facebook-graphi-api-nodejs).

**Comment by bdickason** [comment]
Thanks @sillygwailo! Could you also update the README file so users know this is an optional input field for getSingleShelf? I'll merge once that lands :)

**Comment by sillygwailo** [comment]
I've updated the CoffeeScript files and the example both in the .coffee and in the README.

**Comment by bdickason** [comment]
Thanks!! :+1:

**Pull request merged**
