### PR TITLE
Add search

### PR DESCRIPTION
**Pull request by rharriso**

### CODE REVIEW

**Comment by bdickason** [comment]
@rharriso as you can tell, I'm not doing a great job keeping up with pull requests and maintenance on this repo. Would you be open to helping out by reviewing/testing pull requests and managing the npm project?

**Comment by rharriso** [comment]
@bdickason Sorry I haven't responded yet. I meant to this weekend. I'll get back to you soon.

**Comment by rharriso** [comment]
@bdickason, I think I would like to help out on this project. 
I'm currently working on another that will be using your to some extent.

**Comment by rharriso** [comment]
@bdickason. I'm coming back to this project again. I've reviewed a couple PR's today. If you are still willing. I'd be up for helping out with this project.

**Comment by bdickason** [comment]
Thanks @rharriso! That would be great :) I haven't had time to review things so everyone will appreciate that.

This will be my first project sharing access so let me figure out what I need to do and will make it happen ASAP.

**Comment by bdickason** [comment]
@rharriso just sent you a collaboration request. You should be able to approve/merge PR's once you accept that!

**Pull request merged**
